version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD:computer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data:
