version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD:${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    ports:
      - 8080:8080

  python_app:
    build: .
    env_file:
      - .env  # Specify the .env file to load environment variables
    depends_on:
      - db  # Ensure the Python app waits for the database to be ready
    volumes:
      - .:/Home_Automation  # Mount the current directory to the app container
    working_dir: /Home_Automation  # Set the working directory inside the container

volumes:
  postgres_data:
